### PR TITLE
Add Injector plugin

### PR DESCRIPTION
**Pull request by justinmayer**
After importing the original commits, I made two notable changes:

* Convert structure to namespace plugin format
* Rename plugin setting names for consistency and clarity

The remainder of the changes are related to code style, package publication, and general project infrastructure.

### CODE REVIEW

**Comment by justinmayer** [comment]
@buanzo: After making the changes in this pull request, I haven't had the chance to test the plugin to ensure it functions properly. Would you do some basic testing and make sure the plugin still functions correctly? 😅

**Comment by buanzo** [comment]
Hi! I will review the changes, then I will test it out. It will be done today. Indeed, we are on the same page XD

Thank you!

**Review by buanzo — COMMENTED** [review]
Visual check OK, my name is wrong: Arturo 'Buanzo' Busleiman would be correct, NOT Arturo Busleimanbuanzo. - If you prefer to avoid my nickname (in use since 1995), Arturo Busleiman is fine. Live testing later today.

**Comment by justinmayer** [comment]
Sorry for the copy+paste fail. Fixed in [08ec92e](https://github.com/pelican-plugins/injector/pull/1/commits/08ec92e1dec177e2b5722516b34821458781d53d) and then again in [e36582a](https://github.com/pelican-plugins/injector/pull/1/commits/e36582a86bdb2e8906c73f1bea0adc4a58e07de0).

**Comment by buanzo** [comment]
I have tested the plugin. It worked for p tags, but not for head

The original version of my plugin used the content_object_init signal, but then I decided the article_writer and page_writer ones, at least from the documentation, would probably be sent after integrating to theme. This seems not to be the case.

I might need to modify the plugin to use the get_writer signal.

What do you think, @justinmayer ?

**Comment by buanzo** [comment]
For instance, I could probably use the content_written signal, but that's a bit of a hack, as it happens after the resulting file is created. I will look into Pelican's source code to see if there's a signal that happens after jinja2 rendering and before the file gets written, so I can access the resulting rendered content. Maybe the _finalized ones?

**Comment by buanzo** [comment]
*IF* no signal for post-rendering pre-writing exists, then the hack could be optimized like this:

Currently, the inject_content() function is trying to insert custom code into the HTML content of articles and pages, which works great if the specified tags are found in the content. However, if a tag is not found in the content (which may be the case for tags that are part of the theme template, such as <head>), the injection fails as the tag is not found.

To handle these cases, we could make inject_content() keep track of failed injections and return a list of them. Then, we could connect a new function to the content_written signal, which is triggered after an article or page has been written to disk. This function could attempt to perform the injections that failed in inject_content().

Let me know your thoughts. Thank you Justin!

**Comment by justinmayer** [comment]
After the work I did on this plugin this morning, my open-source time budget/allocation for today has unfortunately been exceeded, and I will be mostly unavailable for the next couple of weeks, so I shall defer to the results of your experimentation related to this latter topic.

That said, perhaps @avaris might have some thoughts to share.

**Comment by buanzo** [comment]
Justin, thanks for the time invested in open source. 

@avaris - I have checked the pelican-seo plugin, and it uses all_generators_finalized and content_written signals.

My proposed workaround to avoid using the content_written signal as much as possible might be the best course of action.

**Comment by buanzo** [comment]
I'm going to integrate your PR, @justinmayer. However, I'll also open an issue to highlight the need for a new signal that addresses the injection related to tags that were missed by the previous signals.

**Comment by buanzo** [comment]
To finish the migration to this organization, I have removed the files from the original repo: https://github.com/buanzo/pelican-injector and replaced the README with a link to this repo.

Thank you @justinmayer

**Comment by avaris** [comment]
Sorry for delayed response, I've been rather busy.

> IF no signal for post-rendering pre-writing exists, then the hack could be optimized like this:

> I'll also open an issue to highlight the need for a new signal that addresses the injection related to tags that were missed by the previous signals.

If I'm missing context please let me know, but based on the discussion here and a quick glance at the plugin description... You are looking for a way to modify *rendered* (after passed to template), right? And, no, there is no signal that is between render and write. Adding one would be somewhat hacky because of the subtle issues from plugin dispatcher (`blinker`), python etc. Essentially you would be passing a string and retrieving the result back. However, this is not chainable (i.e. if multiple plugins connect to this signal), simply because strings are immutable. You could wrap this in a class and make it an attribute so that plugins could replace the attribute value... and that's the hacky part :).

So... currently best (and safest) course of action is
* find the written file
* read it
* change it
* write back

I agree, this is somewhat wasteful.

**Comment by buanzo** [comment]
Hi! Thanks for your reply :)

The code is implemented as described, an early attempt to inject, keeping
track of failed ones for final write signal attempt.

I don't love the implementation, but it works as advertised. :)

cheers!

**Pull request merged**
